# Database
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/bookstore
quarkus.datasource.username=root
quarkus.datasource.password=NikoRiver717
#Ankara06.
# Hibernate ORM (no Panache)
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Optional: show SQL parameters
quarkus.hibernate-orm.format-sql=true
